services:
  frontend:
    container_name: carti-frontend-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5159}
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    restart: unless-stopped
